GPU Usage(Gbyte): 0.6070370674133301
backbone: resnet18
backward(min): 5.391166666666667
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4\checkpoints-epoch=49-train_loss=-0.89.ckpt
config_path: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4
drop_last: true
experiment: Magic_cube
forward(min): 13.098
input_size: 32
linear_knn_top1_accuracy: 0.6981509245377311
linear_top1_accuracy: 0.7116441779110445
linear_top1_average_accuracy: 0.7118624686153648
linear_top3_accuracy: 0.9325337331334332
log_dir: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4
log_path: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4\UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4.csv
loss_func: NegativeCosineSimilarity
max_epochs: 50
memory_bank_size: 4096
model: SimSiam
momentum: false
name: UA_mdSimSiam_Aug1_VMmean_n_ep50_BA128_v4
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim:
- - 2048
  - 512
  - BN
  - RELU
- - 512
  - 2048
  - None
  - None
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 7.1323533177375795
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: true
transform(min): 0.15824999999999997
update(min): 18.853333333333335
view: 4
view_model: mean_n
