GPU Usage(Gbyte): 2.2477025985717773
backbone: resnet18
backward(min): 3.279166666666667
batch_size: 256
checkpoint_dir: experiment_checkpoints/
dataset_dir: D:/Datasets/TinyImageNet/train/
device: cuda
drop_last: true
experiment: Magic_cube
forward(min): 11.769499999999999
input_size: 64
log_dir: experiment_checkpoints/Magic_cube\Base_ImageNet_mdVICReg_VMNone_ep50_v2
loss_func: VICRegLoss
max_epochs: 50
memory_bank_size: 4096
model: VICReg
momentum: false
name: Base_ImageNet_mdVICReg_VMNone_ep50_v2
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 46.47928662697474
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 10.656
update(min): 15.4125
view: 2
view_model: None
