GPU Usage(Gbyte): 2.157956600189209
backbone: resnet18
backward(min): 5.596
batch_size: 256
checkpoint_dir: experiment_checkpoints/
dataset_dir: D:/Datasets/TinyImageNet/train/
device: cuda
drop_last: true
experiment: Magic_cube
forward(min): 11.761500000000002
input_size: 64
log_dir: experiment_checkpoints/Magic_cube\Base_ImageNet_mdSimSiam_VMmean_n_ep50_v4
loss_func: NegativeCosineSimilarity
max_epochs: 50
memory_bank_size: 4096
model: SimSiam
momentum: false
name: Base_ImageNet_mdSimSiam_VMmean_n_ep50_v4
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim:
- - 2048
  - 512
  - BN
  - RELU
- - 512
  - 2048
  - None
  - None
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 70.64017674128215
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: true
transform(min): 29.255
update(min): 17.766666666666666
view: 4
view_model: mean_n
