GPU Usage(Gbyte): 0.921875
backbone: resnet18
backward(min): 2.4451666666666667
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2\checkpoints-epoch=49-train_loss=6.58.ckpt
config_path: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2
drop_last: true
experiment: Magic_cube
forward(min): 10.293166666666668
input_size: 32
linear_knn_top1_accuracy: 0.6346365363463654
linear_top1_accuracy: 0.6531346865313469
linear_top1_average_accuracy: 0.6531288711288712
linear_top3_accuracy: 0.9066093390660934
log_dir: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2
log_path: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2\VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2.csv
loss_func: MoCo
max_epochs: 50
memory_bank_size: 4096
model: MoCo
momentum: true
name: VIEW_LOG2_mdMoCo_VMmean_n_ep50_v2
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 512
  - None
  - RELU
- - 512
  - 512
  - None
  - RELU
- - 512
  - 512
  - None
  - RELU
- - 512
  - 128
  - None
  - None
runing time(min): 25.685462498664855
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 0.11721666666666668
update(min): 13.096499999999999
view: 2
view_model: mean_n
