GPU Usage(Gbyte): 11.107747554779053
backbone: resnet18
backward(min): 0.9424666666666667
batch_size: 256
checkpoint_dir: experiment_checkpoints/
dataset_dir: D:/Datasets/imagenette2-160/train
device: cuda
drop_last: true
experiment: Magic_cube
forward(min): 18.446666666666665
input_size: 128
log_dir: experiment_checkpoints/Magic_cube\Base_ImgNette_mdBYOL_VMNone_ep200_v4
loss_func: NegativeCosineSimilarity
max_epochs: 200
memory_bank_size: 4096
model: BYOL
momentum: true
name: Base_ImgNette_mdBYOL_VMNone_ep200_v4
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim:
- - 256
  - 1024
  - BN
  - RELU
- - 1024
  - 256
  - None
  - None
prjhead_dim:
- - 512
  - 1024
  - BN
  - RELU
- - 1024
  - 256
  - None
  - None
runing time(min): 109.38823711872101
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: true
transform(min): 27.058333333333334
update(min): 19.541666666666668
view: 4
view_model: None
