GPU Usage(Gbyte): 1.7130284309387207
backbone: resnet18
backward(min): 8.993666666666666
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4\checkpoints-epoch=49-train_loss=18.32.ckpt
config_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4
drop_last: true
experiment: Magic_cube
forward(min): 11.2625
input_size: 32
linear_knn_top1_accuracy: 0.587941205879412
linear_top1_accuracy: 0.607039296070393
linear_top1_average_accuracy: 0.6070391608391608
linear_top3_accuracy: 0.8763123687631237
log_dir: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4
log_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4.csv
loss_func: VICRegLoss
max_epochs: 50
memory_bank_size: 4096
model: VICReg
momentum: false
name: VIEW_LOG3_mdVICReg_VMmean_n_ep50_v4
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 34.237905315558116
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 0.13106666666666666
update(min): 20.575
view: 4
view_model: mean_n
