GPU Usage(Gbyte): 10.893752574920654
backbone: resnet18
backward(min): 12.068166666666666
batch_size: 256
checkpoint_dir: experiment_checkpoints/
dataset_dir: D:/Datasets/imagenette2-160/train
device: cuda
drop_last: true
experiment: Magic_cube
forward(min): 14.478666666666667
input_size: 128
log_dir: experiment_checkpoints/Magic_cube\Base_ImgNette_mdBarlowTwins_VMNone_ep200_v4
loss_func: BarlowTwinsLoss
max_epochs: 200
memory_bank_size: 4096
model: BarlowTwins
momentum: false
name: Base_ImgNette_mdBarlowTwins_VMNone_ep200_v4
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - None
  - None
runing time(min): 105.50884206692378
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 19.663333333333334
update(min): 26.678333333333335
view: 4
view_model: None
