GPU Usage(Gbyte): 1.538750171661377
backbone: resnet18
backward(min): 13.744666666666665
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6\checkpoints-epoch=49-train_loss=18.44.ckpt
config_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6
drop_last: true
experiment: Magic_cube
forward(min): 14.332666666666666
input_size: 32
linear_knn_top1_accuracy: 0.5962403759624038
linear_top1_accuracy: 0.6082391760823918
linear_top1_average_accuracy: 0.6082296703296703
linear_top3_accuracy: 0.8789121087891211
log_dir: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6
log_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6.csv
loss_func: VICRegLoss
max_epochs: 50
memory_bank_size: 4096
model: VICReg
momentum: false
name: VIEW_LOG3_mdVICReg_VMmean_n_ep50_v6
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 42.953658417860666
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 0.2006
update(min): 28.403333333333332
view: 6
view_model: mean_n
