GPU Usage(Gbyte): 1.0271306037902832
backbone: resnet18
backward(min): 4.373166666666666
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2\checkpoints-epoch=44-train_loss=18.00.ckpt
config_path: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2
drop_last: true
experiment: Magic_cube
forward(min): 9.298833333333333
input_size: 32
linear_knn_top1_accuracy: 0.44915508449155084
linear_top1_accuracy: 0.46805319468053197
linear_top1_average_accuracy: 0.46803986013986004
linear_top3_accuracy: 0.7894210578942106
log_dir: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2
log_path: experiment_checkpoints/Magic_cube\VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2\VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2.csv
loss_func: VICRegLoss
max_epochs: 50
memory_bank_size: 4096
model: VICReg
momentum: false
name: VIEW_LOG2_mdVICReg_VMmean_n_ep50_v2
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 27.293087232112885
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 0.13568333333333332
update(min): 14.007833333333334
view: 2
view_model: mean_n
