GPU Usage(Gbyte): 1.0177083015441895
backbone: resnet18
backward(min): 2.4810000000000003
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2\checkpoints-epoch=49-train_loss=6.57.ckpt
config_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2
drop_last: true
experiment: Magic_cube
forward(min): 10.333333333333334
input_size: 32
linear_knn_top1_accuracy: 0.6334366563343665
linear_top1_accuracy: 0.644035596440356
linear_top1_average_accuracy: 0.6440297702297703
linear_top3_accuracy: 0.9041095890410958
log_dir: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2
log_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2\VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2.csv
loss_func: MoCo
max_epochs: 50
memory_bank_size: 4096
model: MoCo
momentum: true
name: VIEW_LOG3_mdMoCo_VMmean_n_ep50_v2
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 512
  - None
  - RELU
- - 512
  - 512
  - None
  - RELU
- - 512
  - 512
  - None
  - RELU
- - 512
  - 128
  - None
  - None
runing time(min): 25.84588841199875
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 0.1176
update(min): 13.166166666666667
view: 2
view_model: mean_n
