GPU Usage(Gbyte): 0.8482217788696289
backbone: resnet18
backward(min): 2.2605
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2\checkpoints-epoch=49-train_loss=-0.87.ckpt
config_path: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2
drop_last: true
experiment: Magic_cube
forward(min): 9.969
input_size: 32
linear_knn_top1_accuracy: 0.38980509745127434
linear_top1_accuracy: 0.40929535232383807
linear_top1_average_accuracy: 0.40500752464439377
linear_top3_accuracy: 0.7501249375312344
log_dir: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2
log_path: experiment_checkpoints/Magic_cube\UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2\UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2.csv
loss_func: NegativeCosineSimilarity
max_epochs: 50
memory_bank_size: 4096
model: SimSiam
momentum: false
name: UA_mdSimSiam_Aug3_VMNone_ep50_BA128_v2
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim:
- - 2048
  - 512
  - BN
  - RELU
- - 512
  - 2048
  - None
  - None
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 23.872728300094604
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: true
transform(min): 0.10693333333333334
update(min): 12.564833333333333
view: 2
view_model: None
