GPU Usage(Gbyte): 1.1203827857971191
backbone: resnet18
backward(min): 4.308333333333334
batch_size: 128
checkpoint_dir: experiment_checkpoints/
ckpt_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2\checkpoints-epoch=49-train_loss=17.77.ckpt
config_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2\config.yaml
dataset_dir: D:/Datasets/cifar10/train/
device: cuda
dir_name: VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2
drop_last: true
experiment: Magic_cube
forward(min): 9.0945
input_size: 32
linear_knn_top1_accuracy: 0.4707529247075293
linear_top1_accuracy: 0.4844515548445156
linear_top1_average_accuracy: 0.4844462537462538
linear_top3_accuracy: 0.8023197680231977
log_dir: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2
log_path: experiment_checkpoints/Magic_cube\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2\VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2.csv
loss_func: VICRegLoss
max_epochs: 50
memory_bank_size: 4096
model: VICReg
momentum: false
name: VIEW_LOG3_mdVICReg_VMmean_n_ep50_v2
num_workers: 6
optimizer: SGD
path_to_data_Alex_clothing: D:/Datasets/clothing
path_to_data_sentinel: D:/Datasets/sentinel
path_to_test_TinyImageNet: D:/Datasets/TinyImageNet/test/
path_to_test_cifar10: D:/Datasets/cifar10/test/
path_to_test_imagenet-mini: D:/Datasets/imagenet-mini/val/
path_to_test_xBD: D:/Datasets/xBD/test/
path_to_train_TinyImageNet: D:/Datasets/TinyImageNet/train/
path_to_train_cifar10: D:/Datasets/cifar10/train/
path_to_train_imagenet-mini: D:/Datasets/imagenet-mini/train/
path_to_train_xBD: D:/Datasets/xBD/train/
predhead_dim: []
prjhead_dim:
- - 512
  - 2048
  - BN
  - RELU
- - 2048
  - 2048
  - BN
  - None
runing time(min): 26.759147946039835
samples: 0
schedule: cos
seed: 1
shuffle: true
stop_gradient: false
transform(min): 0.14091666666666666
update(min): 13.715666666666667
view: 2
view_model: mean_n
